BOA-with-elephant/Header-backend

src/main/java/com/header/header/config/BeanConfig.java, src/main/java/com/header/header/domain/menu/dto/MenuCategoryDTO.java, src/main/java/com/header/header/domain/menu/entity/MenuCategory.java, src/main/java/com/header/header/domain/menu/entity/MenuCategoryId.java, src/main/java/com/header/header/domain/menu/repository/MenuCategoryRepository.java, src/main/java/com/header/header/domain/menu/service/MenuCategoryService.java, src/test/java/com/header/header/domain/menu/MenuCategoryRepositoryTests.java
- ** Menu Category Table 은 복합 기본키 사용으로, BeanConfig 클래스에서 복합 기본키 매핑을 위한 TypeMap 설정 추가
Menu Category CRUD 기능 구현하였습니다. → 모든 기능은 특정 샵 기준으로 작동하도록 설정
=> [FEATURE] #12 MenuCategory CRUD 구현

build.gradle
build.gradle 수정(spring security 삽입)
=> [HOTFIX] spring security insert

src/main/java/com/header/header/domain/menu/entity/Menu.java, src/main/java/com/header/header/domain/reservation/converter/ReservationStateConverter.java, src/main/java/com/header/header/domain/reservation/dto/BossResvMenuDTO.java, src/main/java/com/header/header/domain/reservation/dto/BossResvUserDTO.java, src/main/java/com/header/header/domain/reservation/dto/UserReservationDTO.java, src/main/java/com/header/header/domain/reservation/entity/BossReservation.java, src/main/java/com/header/header/domain/reservation/entity/Reservation.java, src/main/java/com/header/header/domain/reservation/enums/ReservationState.java, src/main/java/com/header/header/domain/reservation/projection/UserReservationSummary.java, src/main/java/com/header/header/domain/reservation/repository/BossReservationRepository.java, src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java, src/main/java/com/header/header/domain/reservation/service/BossReservationService.java, src/main/java/com/header/header/domain/reservation/service/UserReservationService.java, src/main/java/com/header/header/domain/user/entity/User.java, src/test/java/com/header/header/domain/reservation/repository/BossReservationRepositoryTests.java, src/test/java/com/header/header/domain/reservation/service/UserReservationTests.java
- 기존에 나뉘어져 있던 BossReservation, UserReservation Entity를 통합하였습니다.
- 통합으로 인해 발생하는 컴파일 에러를 수정하였습니다
- 기존에 UserReservation Entity 관련 기능을 사용하시는 도메인 담당자 분들은 바뀌어진 Entity에 맞게 수정을 요합니다.
- 참고: 기존 Reservation 삭제 -> BossReservation Entity 사용 예정, 필드 타입과 이름까지 모두 변경되었습니다.
closed #48
=> [FIX] #48 BossReservation, UserReservation Entity 통합 및 수정

src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java, src/main/java/com/header/header/domain/reservation/service/BossReservationService.java, src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
- Reservation Entity 통합, Repository 수정, 통합 후 다른 분들 코드에서도 의존성 문제로 버그가 발생하여 기존 상태로 원상복구 하였습니다.
closed  #51
=> [HOTFIX] UserReservation Repository 복구

src/main/java/com/header/header/domain/visitors/DTO/VisitorDetailDTO.java, src/main/java/com/header/header/domain/visitors/DTO/VisitorsDTO.java, src/main/java/com/header/header/domain/visitors/enitity/Visitors.java, src/main/java/com/header/header/domain/visitors/projection/UserFavoriteMenuView.java, src/main/java/com/header/header/domain/visitors/projection/VisitStatisticsView.java, src/main/java/com/header/header/domain/visitors/projection/VisitorWithUserInfoView.java, src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java, src/main/java/com/header/header/domain/visitors/service/VisitorsService.java, src/test/java/com/header/header/domain/visitors/service/VisitorsTests.java
- shop code로 visitors를 조회하여 유저 정보, 유저의 방문 정보, 선호 메뉴 등등 부가 정보를 리스트로 가져오는 Read 코드를 작성하였습니다.
- TestCode로 정상 작동 됨을 확인하였습니다.
=> [FEATURE] #55 Read ShopUserList 구현

src/main/java/com/header/header/domain/user/service/UserService.java, src/main/java/com/header/header/domain/visitors/DTO/VisitorsDTO.java, src/main/java/com/header/header/domain/visitors/service/VisitorsService.java, src/test/java/com/header/header/domain/visitors/service/VisitorsTests.java
- 샵 내 회원을 추가하는 서비스 코드를 작성하였습니다.
- User Service 에서 username,userphone으로 이미 있는 회원인지 조회하는 코드를 작성하였습니다.
``` java
// UserService.java
/**
* 이름과 핸드폰 번호로 userCode를 조회한다.
*
* @param userName 유저 이름
* @param userPhone 유저 핸드폰 번호
* */
public Integer findUserByNameAndPhone(String userName, String userPhone){
User find =  userRepository.findByUserNameAndUserPhone(userName, userPhone);
return find != null ? find.getUserCode() : null;
}
```
user의 phone과 name으로 조회를 하는 부분이 @JUHYE0925 님과 겹쳐서 SSR(단일책임)원칙에 따라 User Entity 조회 및 생성 로직은
User Service가 갖도록 Service 클래스를 생성하였습니다.
``` java
// UserService.java
/**
* dummy user을 추가한다.
* dummy user = 이름과 전화번호만 있는 유령 유저 정보
*
* @param userName 유저 이름
* @param userPhone 유저 핸드폰 번호
* */
@Transactional
public User createUserByNameAndPhone(String userName, String userPhone){ …
```
=> [FEATURE] #59 feature create user 기능 구현

src/main/java/com/header/header/domain/shop/dto/ShopCategoryDTO.java, src/main/java/com/header/header/domain/shop/repository/ShopCategoryRepository.java, src/main/java/com/header/header/domain/shop/service/ShopCategoryService.java, src/test/java/com/header/header/domain/shop/service/ShopCategoryServiceTest.java
- 모든 카테고리 카테고리 코드 순서대로 조회
비동기 요청으로만 쓰일 예정이라 간단하게 전체 조회로 불러오는 것만 구현했습니다.   
혹시 다른 기능이 또 필요할 시 요청 해주세요 ~ 
closed #13
=> [FEATURE] #13 Shop Category Read 기능 완료

src/main/java/com/header/header/auth/config/SecurityConfig.java, src/main/java/com/header/header/auth/controller/MainController.java, src/test/java/com/header/header/domain/user/service/UserFacadeServiceTests.java
=> [Hotfix] 128 hotfix security config permitall change

src/main/java/com/header/header/domain/menu/controller/MenuCategoryController.java, src/main/java/com/header/header/domain/menu/controller/MenuController.java, src/main/java/com/header/header/domain/sales/controller/SalesController.java
- **403 오류 해결**: 프론트엔드에서 `/sales/active` API 호출 시 발생하던 403 Forbidden 오류 해결
- **경로 불일치 문제**: Spring Security 설정에서는 `/my-shops/**` 경로를 `permitAll()`로 허용하고 있었지만, 실제 API 호출은 `/myshop/sales/*` 경로를 사용하여 인증이 요구되는 문제
- **API 경로 통일**: 매출 관련 API 호출 경로를 `/myshop/sales/*`에서 `/my-shops/sales/*`로 변경하여 Spring Security 설정과 일치
=> [HOTFIX] #131 change api path /myshop → /my shops (sales/menu)

src/main/java/com/header/header/domain/message/controller/MessageController.java, src/main/java/com/header/header/domain/message/dto/MessageTemplateDTO.java, src/main/java/com/header/header/domain/message/dto/MessageTemplateRequest.java, src/main/java/com/header/header/domain/message/dto/MessageTemplateSimpleDto.java, src/main/java/com/header/header/domain/message/entity/MessageTemplate.java, src/main/java/com/header/header/domain/message/service/MessageTemplateService.java
- 템플릿 리스트 조회 Service 코드 수정
- 템플릿 추가 API 작성
- 템플릿 수정 API 작성
- 템플릿 삭제 API 작성
메세지 템플릿 등록 테스트
<br>
메세지 템플릿 수정 테스트
<br>
메세지 템플릿 삭제 테스트
=> [FEATURE] #126 feature template manage controller mapping

src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java, src/main/java/com/header/header/domain/reservation/repository/UserReservationRepository.java, src/main/java/com/header/header/domain/reservation/service/UserReservationService.java
예약 논리적 삭제 기능 Controller 연결
예약 논리적 삭제 시 예약 등록 및 예약 정보 수정 시 예약 가능 시간을 불러오는 백엔드 코드에서 예약 취소도 같이 불러올 수 있게 수정
=> [FEATURE] #135 BossReservation Soft Delete

src/main/java/com/header/header/auth/config/SecurityConfig.java, src/main/java/com/header/header/auth/model/dto/TokenDTO.java, src/main/java/com/header/header/auth/model/service/AuthUserService.java, src/main/java/com/header/header/domain/user/controller/UserController.java, src/main/java/com/header/header/domain/user/service/UserFacadeService.java, src/test/java/com/header/header/domain/user/service/UserFacadeServiceTests.java
컨트롤러: 회원 수정에 관한 url "/auth/{user_id}" mapping 추가
로그인 시 JWT 토큰 못 받아오던 것 해결!!!😭
=> [FEATURE] 123 feature add missing controller

src/main/java/com/header/header/domain/sales/controller/SalesController.java
기존에는 매출 컨트롤러에서 직접 예약 서비스의 메소드를 호출하여 예약 상태를 변경 후 매출을 등록하려 했으나, 
이미 구현되어 있는 BossReservationService의 afterProcedure 메소드를 활용하도록 개선
=> [FIX] #152 sales registration afterprocedure integration

src/main/java/com/header/header/auth/model/dto/LoginUserDTO.java, src/main/java/com/header/header/domain/reservation/controller/UserReservationController.java, src/main/java/com/header/header/domain/reservation/projection/UserReservationSummary.java, src/main/java/com/header/header/domain/shop/common/GetUserInfoByAuthDetails.java, src/main/java/com/header/header/domain/shop/controller/AdminShopController.java, src/main/java/com/header/header/domain/shop/controller/ShopController.java, src/main/java/com/header/header/domain/shop/controller/ShopHolidayController.java, src/main/java/com/header/header/domain/shop/enums/ShopHolidayErrorCode.java, src/main/java/com/header/header/domain/shop/service/ShopHolidayService.java, src/main/java/com/header/header/domain/user/entity/User.java, src/main/java/com/header/header/domain/user/projection/UserCode.java, src/main/java/com/header/header/domain/user/repository/MainUserRepository.java, src/test/java/com/header/header/domain/shop/service/ShopHolidayServiceTests.java
- Shop 및 User Reservation 도메인 - 컨트롤러에서 프론트의 헤더 내 인증 정보를 받아오는 인증/인가 처리를 구현했습니다.
=> [FEATURE] #142 Shop 및 User Reservation 도메인 jwt 토큰 인증 처리 추가

src/main/java/com/header/header/config/AsyncConfig.java, src/main/java/com/header/header/domain/message/controller/MessageController.java
- FE 요청 방식과 BE에서 API 요청 받는 방식이 일치하지 않아서 수정하였습니다.
=> [HOTFIX] 메세지 템플릿 삭제 API requestBody 전달 방식에서 param으로 변경

src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java, src/main/java/com/header/header/domain/reservation/service/BossReservationService.java, src/main/java/com/header/header/domain/user/repository/MainUserRepository.java, src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java, src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
시술 완료 처리
메시지 전송 메소드 추가(일단 주석처리 했습니다.)
=> [FEATURE] #151 BossReservation Completed Procedure

src/main/java/com/header/header/auth/config/JwtTokenProvider.java, src/main/java/com/header/header/auth/config/SecurityConfig.java, src/main/java/com/header/header/common/exception/GlobalExeptionHandlerForApiResponse.java, src/main/java/com/header/header/config/AsyncConfig.java, src/main/java/com/header/header/domain/message/controller/MessageController.java, src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java, src/main/java/com/header/header/domain/reservation/service/BossReservationService.java, src/main/java/com/header/header/domain/user/controller/UserController.java, src/main/java/com/header/header/domain/user/repository/MainUserRepository.java, src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java, src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
[MERGE] Develope 브랜치 master에 머지합니다
=> [MERGE] Develope 브랜치 master에 머지

.github/workflows/deploy.yml, Dockerfile, compose.yaml, init.sql, src/main/java/com/header/header/domain/reservation/controller/BossReservationController.java, src/main/java/com/header/header/domain/reservation/service/BossReservationService.java, src/main/java/com/header/header/domain/user/dto/UserDTO.java, src/main/java/com/header/header/domain/user/entity/User.java, src/main/java/com/header/header/domain/user/repository/MainUserRepository.java, src/main/java/com/header/header/domain/user/service/UserService.java, src/main/java/com/header/header/domain/visitors/repository/VisitorsRepository.java, src/main/java/com/header/header/domain/visitors/service/VisitorsService.java
CI/CD 코드 수정 및 메시지 발송 코드 추가(아직 오류나서 주석처리하고 올렸습니다.)
=> [FIX] #166 / EDIT CI/CD

.github/workflows/deploy.yml, .gitignore, docker-compose.yml, settings.gradle, src/main/java/com/header/header/config/WebMvcConfig.java
=> [FIX] #170 Add settings.gradle

.github/workflows/deploy.yml
DEPLOY.YML 파일 수정 (DOCKER-COMPOSE 명령어 수정, 계정을 docker 그룹에 추가)
=> [FIX] #178 Modify Deploy.yml File

.github/workflows/deploy.yml, docker-compose.yml, llm/Dockerfile, llm/app/core/redis_manager.py
로컬에서 DOCKER 띄었을 때 redis_url이 localhost로 잡혀서 계속 에러가 남.
해당 url을 개발 시에는 localhost, 배포 환경에서는 localhost로 수정함.
=> [FIX] #238 Fix Redis Deploy File

llm/requirements.txt
requirements.txt 파일에 cachtools 패키지 추가
=> [FEATURE] #265 Add Cachtools To The Requirements.txt File

docker-compose.yml, llm/app/core/config.py, llm/app/services/user_reservation_service.py, src/main/java/com/header/header/domain/chatbot/service/ChatbotService.java, src/main/java/com/header/header/domain/reservation/service/BossReservationChatbotService.java
1.  env 파일 환경에 따라 분리
2. llm 프로젝트 하드 코딩된 url 수정
3. docker-compse 및 yml에 llm 환경 변수 추가
=> [FEAT] #282 Dynamic environment configuration for service URLs

llm/app/core/config.py
새로 구현한 기능 및 주요 변경점
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다. 최대한 자세히 적어주세요!
- Docker 컨테이너 환경과 로컬 환경에서 Redis 연결을 안정적으로 구성하기 위함
- 기존 `is_docker()` 조건문 기반의 URL 결정 방식에서 **환경 변수 기반** 방식으로 전환
- LLM 컨테이너가 항상 `.env` 파일의 설정을 읽도록 개선
기존:
```python
redis_url: str = Field(default=f"redis://{'header-redis' if is_docker() else 'localhost'}:6379")
```
변경:
```
redis_url: str = Field(
default_factory=lambda: f"redis://{os.getenv('SPRING_REDIS_HOST', 'localhost')}:{os.getenv('SPRING_REDIS_PORT', 6379)}"
)
```
=> [FIX] #308 Fix Edit Config.py - LLM Redis 설정 개선 

src/main/java/com/header/header/domain/reservation/dto/BossResvProjectionDTO.java
=> [FIX] #325 Fix BossReservation Error
